name: Security - SAST Scanning

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:

    name: Semgrep SAST

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Semgrep
        run: |
          chmod +x ../scripts/install-semgrep.sh
          ../scripts/install-semgrep.sh

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config auto \
            --sarif \
            --output semgrep.sarif \
            .

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: app/semgrep.sarif