name: Security - SCA

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trivy-fs:
    name: Trivy Filesystem Scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Download
        run: |
            VERSION=0.70.0
            URL="https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz"
            echo "$URL"
            curl -I -L "$URL"

      - name: Install Trivy
        run: |
          chmod +x scripts/install-trivy.sh
          ./scripts/install-trivy.sh

      - name: Run Trivy Filesystem Scan
        run: |
          trivy fs \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            .