name: Security - SCA

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trivy-fs:
    name: Trivy Filesystem Scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          chmod +x scripts/install-trivy.sh
          ./scripts/install-trivy.sh

      - name: Run Trivy Filesystem Scan
        run: |
          trivy fs \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            .