name: Security - Secret Scanning

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gitleaks:
    name: Secret Scanning

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION=8.24.3

          wget https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz

          tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz

          sudo mv gitleaks /usr/local/bin/

          gitleaks version

      - name: Scan Repository
        run: |
          gitleaks detect \
            --no-git \
            --source . \
            --verbose